{...}: {
  imports = [
    ./bash.nix
    ./bat.nix
    ./browser.nix
    ./btm.nix
    ./btop.nix
    ./cava.nix
    ./codium.nix
    ./direnv.nix
    ./discord.nix
    ./emoji.nix
    ./fastfetch
    ./gh.nix
    ./ghostty.nix
    ./git.nix
    ./gtk.nix
    ./hyprland
    ./kitty.nix
    ./lazygit.nix
    ./nano.nix
    ./nvim
    ./obsidian.nix
    ./rofi
    ./qt.nix
    ./scripts
    ./starship.nix
    ./stylix.nix
    ./swaync.nix
    ./virtmanager.nix
    ./waybar
    ./wlogout
    ./xdg.nix
    ./yazi.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
